<?php

namespace backend\models;

/**
 * This is the model class for table "news_category".
 *
 * @property integer $newsCatId
 * @property string $newsCatName
 * @property integer $parentId
 * @property integer $status
 * @property integer $dateCreate
 */
class NewsCategory extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public $time_form;
    public static function tableName()
    {
        return 'news_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
//            ['time_form','CustomerDate','on'=>['thucthi','update']],
            [['newsCatName'], 'required', 'message' => '{attribute} không được để trống'],
            [['parentId', 'status', 'dateCreate', 'updateAt'], 'integer'],
            [['newsCatName','time_form'], 'string', 'max' => 255],
            [['newsCatName'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'newsCatId' => 'ID',
            'newsCatName' => 'Danh mục tin tức',
            'parentId' => 'Danh mục cha',
            'status' => 'Trạng thái',
            'dateCreate' => 'Ngày khởi tạo',
            'updateAt' => 'Ngày cập nhật',
        ];
    }
//    function beforeSave($insert)
//    {
//        if($this->scenario == 'thucthi') {
//            $this->dateCreate = time();
//        }
//        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
//    }
//
//    public function CustomerDate() {
//        if($this->time_form) {
//
//            /*
//             * validation time
//             * tạo lại kiểu dữ liệu cho dateCreate cho đúng kiểu dữ liệu
//             */
//            $this->dateCreate = $this->time_form;
//        }
//        $this->addError('time_form','Bạn chưa nhập thời gian');
//        return false;
//    }

    public $data;

    public function getNewsCategory($parent = null, $level = "")
    {

        if ($parent == null) {
            $result = NewsCategory::find()
                ->where(['is', 'parentId', null])
                ->asArray()
                ->all();
        } else {
            $result = NewsCategory::find()
                ->where('parentId = :parent', ['parent' => $parent])
                ->asArray()
                ->all();
        }

        $level .= "|--";
        foreach ($result as $value) {
            if ($parent == null) {
                $level = "";
            }
            $this->data[$value["newsCatId"]] = $level . $value["newsCatName"];
            self::getNewsCategory($value["newsCatId"], $level); // đệ quy gọi lại hàm chính nó
        }
        return $this->data;
    }

    public function getNewsCategoryBy($id)
    {
        if ($id == null) {
            return "Root";
        } else {
            $data = NewsCategory::find()->asArray()->where('newsCatId=:newsCatId', ['newsCatId' => $id])->one();
            return $data["newsCatName"];
        }
    }
}
